- name: all
  hosts: all
  gather_facts: false
  sudo: true
  roles:
    - shared-host-file
    - docker

- name: cassandra servers
  hosts: cassandra
  gather_facts: false
  sudo: true
  roles:
    - cassandra

- name: datastax opscenter
  hosts: datastax-opscenter
  gather_facts: false
  sudo: true
  roles:
    - datastax-opscenter
