- name: all
  hosts: all
  gather_facts: false
  sudo: true
  roles:
    - shared-host-file


- name: cassandra servers
  hosts: cassandra
  gather_facts: false
  sudo: true
  roles:
    - oracle-java7
    - storage
    - datastax-cassandra

- name: datastax opscenter
  hosts: datastax-opscenter
  gather_facts: false
  sudo: true
  roles:
    - docker
    - datastax-opscenter
